//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOOSportTovars.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tovar()
        {
            this.TovarZakaz = new HashSet<TovarZakaz>();
        }
    
        public string Articyl { get; set; }
        public string NaimenovanieTovara { get; set; }
        public Nullable<int> EdinicaIzmereniaID { get; set; }
        public Nullable<decimal> Stoimoct { get; set; }
        public Nullable<int> MaxSkidka { get; set; }
        public Nullable<int> ProizvoditelID { get; set; }
        public Nullable<int> PostavchikID { get; set; }
        public Nullable<int> KategoriaID { get; set; }
        public Nullable<int> Skidka { get; set; }
        public Nullable<int> KolichestvoTovara { get; set; }
        public string Opisanie { get; set; }
        public string Image { get; set; }
    
        public virtual EdinicaIzmerenia EdinicaIzmerenia { get; set; }
        public virtual Kategoria Kategoria { get; set; }
        public virtual Postavchik Postavchik { get; set; }
        public virtual Proizvoditel Proizvoditel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TovarZakaz> TovarZakaz { get; set; }
    }
}
