//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOOSportTovars.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TovarZakaz
    {
        public string Articyl { get; set; }
        public int ZakazID { get; set; }
        public Nullable<int> KolichestvoTovara { get; set; }
    
        public virtual Tovar Tovar { get; set; }
        public virtual Zakaz Zakaz { get; set; }
    }
}
