//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOOSportTovars.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zakaz()
        {
            this.TovarZakaz = new HashSet<TovarZakaz>();
        }
    
        public int ZakazID { get; set; }
        public string SostavZakaza { get; set; }
        public Nullable<System.DateTime> DateZakaza { get; set; }
        public Nullable<System.DateTime> DateVudachi { get; set; }
        public Nullable<int> PynktVudachiID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string FIOKlienta { get; set; }
        public Nullable<int> KodPoluchenia { get; set; }
        public string StatusZakaza { get; set; }
    
        public virtual PynktVudachi PynktVudachi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TovarZakaz> TovarZakaz { get; set; }
        public virtual User User { get; set; }
    }
}
